### ISSUE TITLE
Segmention fault

### ISSUE THREAD

**Issue by stv0g** [czerwonk/bird_exporter#34]
bird_exporter: 70add87095a1d57c850adff6b333df80602582a7
bird: 2.0.7 

CLI args: `/usr/local/bin/bird_exporter -format.new=true -bird.v2 -bird.socket=/var/run/bird/bird.ctl`

```
May 10 19:59:00 edgy.0l.de bird_exporter[1988644]: time="2020-05-10T19:59:00+02:00" level=info msg="Starting bird exporter (Version: 1.2.5)\n" source="main.go:63"
May 10 19:59:00 edgy.0l.de bird_exporter[1988644]: time="2020-05-10T19:59:00+02:00" level=info msg="Listening for /metrics on :9324\n" source="main.go:82"
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: panic: runtime error: invalid memory address or nil pointer dereference
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d4918]
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: goroutine 10 [running]:
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/parser.parseLineForDescription(0xc0001948c0)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/parser/parser.go:114 +0xa8
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/parser.ParseProtocols(0xc0002a0000, 0x1b86f, 0x1e000, 0x0, 0x0, 0x1b86f, 0x1e000, 0x0)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/parser/parser.go:67 +0x200
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/client.(*BirdClient).protocolsFromSocket(0xc0000100f8, 0x7ffee4cb1f33, 0x16, 0x0, 0x0, 0x0, 0xc0000a0e70, 0x444ffe, 0xc0000b4b90, 0xc>
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/client/bird_client.go:76 +0xc4
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/client.(*BirdClient).protocolsFromBird(0xc0000100f8, 0xc0000b4b90, 0x1, 0x1, 0x1, 0xc0000b4b90, 0x0, 0x1, 0x0)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/client/bird_client.go:59 +0xee
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/client.(*BirdClient).GetProtocols(0xc0000100f8, 0x0, 0x0, 0x0, 0x0, 0x0)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/client/bird_client.go:40 +0x9c
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: main.(*MetricCollector).Collect(0xc00000f4c0, 0xc0000c8900)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/metric_collector.go:82 +0x36
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: github.com/czerwonk/bird_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc000022670, 0xc0000c8900, 0x974620, 0xc00000f4c0)
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x6b
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]: created by github.com/czerwonk/bird_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May 10 19:59:02 edgy.0l.de bird_exporter[1988644]:         /root/go/src/github.com/czerwonk/bird_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:431 +0x2e9
```

**Comment by stv0g** [comment]
Some more debugging reveals that `c.current` is nil:

```
(gdb) run -format.new=true -bird.v2 -bird.socket=/var/run/bird/bird.ctl
Starting program: /usr/local/bin/bird_exporter -format.new=true -bird.v2 -bird.socket=/var/run/bird/bird.ctl
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.30-11.fc31.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff5b6b700 (LWP 1108503)]
[New Thread 0x7ffff536a700 (LWP 1108504)]
[New Thread 0x7ffff4b69700 (LWP 1108505)]
[New Thread 0x7fffeffff700 (LWP 1108506)]
[New Thread 0x7fffef7fe700 (LWP 1108507)]
INFO[0000] Starting bird exporter (Version: 1.2.5)
      source="main.go:63"
INFO[0000] Listening for /metrics on :9324
              source="main.go:82"

Thread 5 "bird_exporter" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff700 (LWP 1108506)]
0x00000000007d4918 in github.com/czerwonk/bird_exporter/parser.parseLineForDescription (c=0xc0001d2870) at /root/go/src/github.com/czerwonk/bird_exporter/parser/parser.go:114
114		c.current.Description = strings.Join(match[1:], " ")
(gdb) print c.current
$2 = (github.com/czerwonk/bird_exporter/protocol.Protocol *) 0x0
```
